[package]
name = "stdr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
mpsc = "0.2.0"
ratatui = "0.23.0"
thread = "0.1.0"
